# Generated by Django 5.2.17 on 2026-09-29 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('price_above', 'Price crosses above'), ('price_below', 'Price crosses below'), ('price_move', 'Sudden move'), ('bot_trade', 'Bot trades'), ('stop_hit', 'Stop or take profit hit'), ('bot_error', 'Bot or engine problem'), ('research_done', 'Research report finished'), ('daily_summary', 'Daily summary')], max_length=20)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('once', models.BooleanField(default=False)),
                ('cooldown_minutes', models.PositiveIntegerField(default=0)),
                ('last_fired_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='trading.tradingaccount')),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='trading.bot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['kind', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('delivered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='alerts.alertrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
