# Generated by Django 5.2.17 on 2026-09-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_alertrule_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrule',
            name='kind',
            field=models.CharField(choices=[('price_above', 'Price crosses above'), ('price_below', 'Price crosses below'), ('price_move', 'Sudden move'), ('recommendation', 'MT5 recommendations'), ('near_miss', 'Near misses'), ('repeat_signal', 'Entry signal while in a trade'), ('bot_trade', 'Bot trades'), ('stop_hit', 'Stop or take profit hit'), ('bot_error', 'Bot or engine problem'), ('research_done', 'Research report finished'), ('daily_summary', 'Daily summary')], max_length=20),
        ),
    ]
