# Generated by Django 5.2.17 on 2026-09-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_enable_repeat_signal_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertevent',
            name='dismissed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
