/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Accounts */
        get: operations["trading_api_list_accounts"];
        put?: never;
        /** Create Account */
        post: operations["trading_api_create_account"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Account */
        get: operations["trading_api_get_account"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{account_id}/equity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Account Equity */
        get: operations["trading_api_account_equity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{account_id}/funds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move Funds */
        post: operations["trading_api_move_funds"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{account_id}/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Account Ledger */
        get: operations["trading_api_account_ledger"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/defaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Defaults */
        post: operations["alerts_api_defaults"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["alerts_api_list_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rules */
        get: operations["alerts_api_list_rules"];
        put?: never;
        /** Create Rule */
        post: operations["alerts_api_create_rule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Rule */
        put: operations["alerts_api_update_rule"];
        post?: never;
        /** Delete Rule */
        delete: operations["alerts_api_delete_rule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/telegram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Telegram */
        get: operations["alerts_api_get_telegram"];
        /** Set Telegram */
        put: operations["alerts_api_set_telegram"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/telegram/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Telegram */
        post: operations["alerts_api_test_telegram"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit */
        get: operations["core_api_list_audit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/2fa/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Two Factor Confirm */
        post: operations["core_api_two_factor_confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/2fa/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Two Factor Setup */
        post: operations["core_api_two_factor_setup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Csrf
         * @description Sets the CSRF cookie; the frontend calls this once on load.
         */
        get: operations["core_api_csrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login View */
        post: operations["core_api_login_view"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout View */
        post: operations["core_api_logout_view"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["core_api_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["core_api_change_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Bots */
        get: operations["trading_api_list_bots"];
        put?: never;
        /** New Bot */
        post: operations["trading_api_new_bot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bots/{bot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bot */
        get: operations["trading_api_get_bot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bots/{bot_id}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bot Decisions */
        get: operations["trading_api_bot_decisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bots/{bot_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Bot Status */
        post: operations["trading_api_change_bot_status"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Candles */
        get: operations["trading_api_get_candles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Fills */
        get: operations["trading_api_list_fills"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Orders */
        get: operations["trading_api_list_orders"];
        put?: never;
        /**
         * Place Order
         * @description Manual orders always go to the account's manual book; bots trade
         *     their own books through the engine.
         */
        post: operations["trading_api_place_order"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{order_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["trading_api_cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Positions */
        get: operations["trading_api_list_positions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/positions/{position_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close */
        post: operations["trading_api_close"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/positions/{position_id}/protection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Protection */
        put: operations["trading_api_update_protection"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Quote */
        get: operations["trading_api_get_quote"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Experiments */
        get: operations["research_api_list_experiments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/experiments/{experiment_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decide
         * @description The only way an experiment gets a verdict: a person records it.
         */
        post: operations["research_api_decide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["research_api_list_jobs"];
        put?: never;
        /** Create Job */
        post: operations["research_api_create_job"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["research_api_get_job"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/lifecycle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lifecycle */
        get: operations["research_api_lifecycle"];
        put?: never;
        /** Set Lifecycle */
        post: operations["research_api_set_lifecycle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/shadow-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Shadow History */
        get: operations["research_api_shadow_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Strategies */
        get: operations["trading_api_list_strategies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System Status */
        get: operations["trading_api_system_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["core_api_list_users"];
        put?: never;
        /** Create User */
        post: operations["core_api_create_user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["core_api_update_user"];
        trace?: never;
    };
    "/api/users/{user_id}/grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Grants
         * @description Replaces the user's grants with exactly this list.
         */
        put: operations["core_api_set_grants"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/venues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Venues */
        get: operations["trading_api_list_venues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountIn */
        AccountIn: {
            /**
             * Initial Deposit
             * @default 10000
             */
            initial_deposit: number | string;
            /**
             * Mode
             * @default paper
             */
            mode: string;
            /** Name */
            name: string;
            /**
             * Venue
             * @default quidax_spot
             */
            venue: string;
        };
        /** AccountOut */
        AccountOut: {
            /** Books */
            books: components["schemas"]["BookOut"][];
            /** Can Trade */
            can_trade: boolean;
            /** Cash */
            cash: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Equity */
            equity: number | null;
            /** Halted */
            halted: boolean;
            /** Halted Reason */
            halted_reason: string;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            /** Mode */
            mode: string;
            /** Name */
            name: string;
            venue: components["schemas"]["VenueOut"];
        };
        /** AuditOut */
        AuditOut: {
            /** Account Id */
            account_id: number | null;
            /** Action */
            action: string;
            /** Actor */
            actor: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Data */
            data: {
                [key: string]: unknown;
            };
            /** Id */
            id: number;
            /** Ip */
            ip: string | null;
            /** Target */
            target: string;
        };
        /** BookOut */
        BookOut: {
            /** Balances */
            balances: {
                [key: string]: number;
            };
            /** Book */
            book: string;
            /** Bot Id */
            bot_id: number | null;
            /** Equity */
            equity: number | null;
            /** Label */
            label: string;
        };
        /** BotIn */
        BotIn: {
            /** Account Id */
            account_id: number;
            /** Allocation */
            allocation: number | string;
            /** Name */
            name: string;
            /**
             * Params
             * @default {}
             */
            params: {
                [key: string]: unknown;
            };
            /**
             * Risk Pct
             * @default 0.01
             */
            risk_pct: number;
            /**
             * Start
             * @default true
             */
            start: boolean;
            /** Strategy */
            strategy: string;
            /**
             * Symbol
             * @default BTC/USDT
             */
            symbol: string;
            /**
             * Timeframe
             * @default 4h
             */
            timeframe: string;
        };
        /** BotOut */
        BotOut: {
            /** Account Id */
            account_id: number;
            /** Account Mode */
            account_mode: string;
            /** Account Name */
            account_name: string;
            /** Allocation */
            allocation: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Equity */
            equity: number | null;
            /** Id */
            id: number;
            /** Invested Weight */
            invested_weight: number | null;
            /** Last Bar At */
            last_bar_at: string | null;
            last_decision: components["schemas"]["DecisionOut"] | null;
            /** Last Run At */
            last_run_at: string | null;
            /** Name */
            name: string;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /** Pnl */
            pnl: number | null;
            /** Position Quantity */
            position_quantity: number;
            /** Position Stop */
            position_stop: number | null;
            /** Risk Pct */
            risk_pct: number;
            /** Status */
            status: string;
            /** Status Reason */
            status_reason: string;
            /** Strategy */
            strategy: string;
            /** Strategy Kind */
            strategy_kind: string;
            /** Symbol */
            symbol: string;
            /** Timeframe */
            timeframe: string;
        };
        /** BotStatusIn */
        BotStatusIn: {
            /**
             * Reason
             * @default
             */
            reason: string;
            /** Status */
            status: string;
        };
        /** CandleOut */
        CandleOut: {
            /** Close */
            close: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Open */
            open: number;
            /** Time */
            time: number;
            /** Volume */
            volume: number;
        };
        /** DecisionIn */
        DecisionIn: {
            /** Decision */
            decision: string;
            /** Reason */
            reason: string;
        };
        /** DecisionOut */
        DecisionOut: {
            /** Action */
            action: string;
            /**
             * Bar Time
             * Format: date-time
             */
            bar_time: string;
            /** Diagnosis */
            diagnosis: {
                [key: string]: unknown;
            };
            /** Id */
            id: number;
            /** Order Id */
            order_id: number | null;
            /** Price */
            price: number | null;
            /** Reason */
            reason: string;
        };
        /** EquityPoint */
        EquityPoint: {
            /** Equity */
            equity: number;
            /** Time */
            time: number;
        };
        /** EventOut */
        EventOut: {
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Delivered */
            delivered: boolean;
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Title */
            title: string;
        };
        /** ExperimentOut */
        ExperimentOut: {
            /** Config Hash */
            config_hash: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Decision */
            decision: string;
            /** Decision Reason */
            decision_reason: string;
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Result */
            result: {
                [key: string]: unknown;
            };
            /** Strategy */
            strategy: string;
            /** Strategy Label */
            strategy_label: string;
            /** Symbol */
            symbol: string;
            /** Timeframe */
            timeframe: string;
            /** Touched Holdout */
            touched_holdout: boolean;
            /** Window End */
            window_end: string;
            /** Window Start */
            window_start: string;
        };
        /** ExperimentPage */
        ExperimentPage: {
            /** By Kind */
            by_kind: {
                [key: string]: number;
            };
            /** Items */
            items: components["schemas"]["ExperimentOut"][];
            /** Total */
            total: number;
        };
        /** FillOut */
        FillOut: {
            /** Fee */
            fee: number;
            /** Liquidity */
            liquidity: string;
            /** Price */
            price: number;
            /** Quantity */
            quantity: number;
            /**
             * Time
             * Format: date-time
             */
            time: string;
        };
        /** FundsIn */
        FundsIn: {
            /** Amount */
            amount: number | string;
            /**
             * Withdraw
             * @default false
             */
            withdraw: boolean;
        };
        /** GrantIn */
        GrantIn: {
            /** Account Id */
            account_id: number;
            /** Role */
            role: string;
        };
        /** GrantOut */
        GrantOut: {
            /** Account Id */
            account_id: number;
            /** Account Name */
            account_name: string;
            /** Role */
            role: string;
        };
        /** JobIn */
        JobIn: {
            /**
             * Baseline
             * @default donchian
             */
            baseline: string;
            /**
             * Params
             * @default {}
             */
            params: {
                [key: string]: unknown[];
            };
            /** Strategy */
            strategy: string;
            /**
             * Symbol
             * @default BTC/USDT
             */
            symbol: string;
            /**
             * Timeframe
             * @default 4h
             */
            timeframe: string;
        };
        /** JobOut */
        JobOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error: string;
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /** Result */
            result: {
                [key: string]: unknown;
            };
            /** Started At */
            started_at: string | null;
            /** Status */
            status: string;
        };
        /** LedgerOut */
        LedgerOut: {
            /** Amount */
            amount: number;
            /** Asset */
            asset: string;
            /** Book */
            book: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Note */
            note: string;
            /** Order Id */
            order_id: number | null;
        };
        /** LifecycleIn */
        LifecycleIn: {
            /** Label */
            label: string;
            /**
             * Note
             * @default
             */
            note: string;
            /** Stage */
            stage: string;
        };
        /** LifecycleOut */
        LifecycleOut: {
            /** Label */
            label: string;
            /** Note */
            note: string;
            /** Stage */
            stage: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** LifecyclePage */
        LifecyclePage: {
            /** Items */
            items: components["schemas"]["LifecycleOut"][];
            /** Stages */
            stages: string[];
        };
        /** LoginIn */
        LoginIn: {
            /** Otp */
            otp?: string | null;
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** MeOut */
        MeOut: {
            /** Email */
            email: string;
            /** Id */
            id: number;
            /** Needs 2Fa Setup */
            needs_2fa_setup: boolean;
            /** Role */
            role: string;
            /** Two Factor Enabled */
            two_factor_enabled: boolean;
            /** Two Factor Verified */
            two_factor_verified: boolean;
            /** Username */
            username: string;
        };
        /** OrderIn */
        OrderIn: {
            /** Account Id */
            account_id: number;
            /** Limit Price */
            limit_price?: number | string | null;
            /**
             * Note
             * @default
             */
            note: string;
            /**
             * Order Type
             * @default market
             */
            order_type: string;
            /** Quantity */
            quantity: number | string;
            /** Side */
            side: string;
            /** Stop Price */
            stop_price?: number | string | null;
            /**
             * Symbol
             * @default BTC/USDT
             */
            symbol: string;
            /** Take Profit */
            take_profit?: number | string | null;
        };
        /** OrderOut */
        OrderOut: {
            /** Account Id */
            account_id: number;
            /** Average Price */
            average_price: number | null;
            /** Book */
            book: string;
            /** Book Label */
            book_label: string;
            /** Bot Id */
            bot_id: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Fees */
            fees: number;
            /** Filled Quantity */
            filled_quantity: number;
            /** Fills */
            fills: components["schemas"]["FillOut"][];
            /** Id */
            id: number;
            /** Limit Price */
            limit_price: number | null;
            /** Order Type */
            order_type: string;
            /** Placed By */
            placed_by: string | null;
            /** Quantity */
            quantity: number;
            /** Reason */
            reason: string;
            /** Reject Reason */
            reject_reason: string;
            /** Side */
            side: string;
            /** Source */
            source: string;
            /** Status */
            status: string;
            /** Stop Price */
            stop_price: number | null;
            /** Symbol */
            symbol: string;
            /** Take Profit */
            take_profit: number | null;
        };
        /** PasswordIn */
        PasswordIn: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** PositionOut */
        PositionOut: {
            /** Account Id */
            account_id: number;
            /** Average Price */
            average_price: number;
            /** Book */
            book: string;
            /** Book Label */
            book_label: string;
            /** Bot Id */
            bot_id: number | null;
            /** Direction */
            direction: string;
            /** Id */
            id: number;
            /** Mark Price */
            mark_price: number | null;
            /** Opened At */
            opened_at: string | null;
            /** Quantity */
            quantity: number;
            /** Realized Pnl */
            realized_pnl: number;
            /** Stop Price */
            stop_price: number | null;
            /** Symbol */
            symbol: string;
            /** Take Profit */
            take_profit: number | null;
            /** Unrealized Pnl */
            unrealized_pnl: number | null;
        };
        /** ProtectionIn */
        ProtectionIn: {
            /** Stop Price */
            stop_price?: number | string | null;
            /** Take Profit */
            take_profit?: number | string | null;
        };
        /** QuoteOut */
        QuoteOut: {
            /** Ask */
            ask: number;
            /** Bid */
            bid: number;
            /** Last */
            last: number;
            /** Symbol */
            symbol: string;
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Venue */
            venue: string;
        };
        /** RuleIn */
        RuleIn: {
            /** Account Id */
            account_id?: number | null;
            /** Bot Id */
            bot_id?: number | null;
            /**
             * Cooldown Minutes
             * @default 0
             */
            cooldown_minutes: number;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Kind */
            kind: string;
            /**
             * Note
             * @default
             */
            note: string;
            /**
             * Once
             * @default false
             */
            once: boolean;
            /**
             * Params
             * @default {}
             */
            params: {
                [key: string]: unknown;
            };
        };
        /** RuleOut */
        RuleOut: {
            /** Account Id */
            account_id: number | null;
            /** Bot Id */
            bot_id: number | null;
            /** Bot Name */
            bot_name: string | null;
            /** Cooldown Minutes */
            cooldown_minutes: number;
            /** Enabled */
            enabled: boolean;
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Kind Label */
            kind_label: string;
            /** Last Fired At */
            last_fired_at: string | null;
            /** Note */
            note: string;
            /** Once */
            once: boolean;
            /** Params */
            params: {
                [key: string]: unknown;
            };
        };
        /** ShadowHistory */
        ShadowHistory: {
            /** Rebalances */
            rebalances: components["schemas"]["ShadowRebalanceOut"][];
            /** Trades */
            trades: components["schemas"]["ShadowTradeOut"][];
        };
        /** ShadowRebalanceOut */
        ShadowRebalanceOut: {
            /**
             * Bar Time
             * Format: date-time
             */
            bar_time: string;
            /** Equity */
            equity: number;
            /** From Weight */
            from_weight: number;
            /** Price */
            price: number;
            /** Strategy Label */
            strategy_label: string;
            /** Timeframe */
            timeframe: string;
            /** To Weight */
            to_weight: number;
        };
        /** ShadowTradeOut */
        ShadowTradeOut: {
            /** Direction */
            direction: string;
            /** Entry Price */
            entry_price: number;
            /**
             * Entry Time
             * Format: date-time
             */
            entry_time: string;
            /** Exit Price */
            exit_price: number;
            /** Exit Reason */
            exit_reason: string;
            /**
             * Exit Time
             * Format: date-time
             */
            exit_time: string;
            /** Pnl Pct */
            pnl_pct: number;
            /** Strategy Label */
            strategy_label: string;
            /** Symbol */
            symbol: string;
            /** Timeframe */
            timeframe: string;
        };
        /** StrategyOut */
        StrategyOut: {
            /** Can Short */
            can_short: boolean;
            /** Defaults */
            defaults: {
                [key: string]: unknown;
            };
            /** Description */
            description: string;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
        };
        /** SystemOut */
        SystemOut: {
            /** Engine Healthy */
            engine_healthy: boolean;
            /** Engine Last Seen */
            engine_last_seen: string | null;
            /** Require 2Fa */
            require_2fa: boolean;
            /**
             * Server Time
             * Format: date-time
             */
            server_time: string;
        };
        /** TelegramIn */
        TelegramIn: {
            /** Chat Id */
            chat_id: string;
        };
        /** TelegramOut */
        TelegramOut: {
            /** Bot Configured */
            bot_configured: boolean;
            /** Chat Id */
            chat_id: string;
            /** Uses Default Chat */
            uses_default_chat: boolean;
        };
        /** TokenIn */
        TokenIn: {
            /** Token */
            token: string;
        };
        /** TradeOut */
        TradeOut: {
            /** Account Id */
            account_id: number;
            /** Book Label */
            book_label: string;
            /** Fee */
            fee: number;
            /** Id */
            id: number;
            /** Liquidity */
            liquidity: string;
            /** Order Id */
            order_id: number;
            /** Price */
            price: number;
            /** Quantity */
            quantity: number;
            /** Side */
            side: string;
            /** Source */
            source: string;
            /** Symbol */
            symbol: string;
            /**
             * Time
             * Format: date-time
             */
            time: string;
        };
        /** TwoFactorSetupOut */
        TwoFactorSetupOut: {
            /** Otpauth Uri */
            otpauth_uri: string;
            /** Qr Svg */
            qr_svg: string;
        };
        /** UserIn */
        UserIn: {
            /**
             * Email
             * @default
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Role
             * @default viewer
             */
            role: string;
            /** Username */
            username: string;
        };
        /** UserOut */
        UserOut: {
            /** Email */
            email: string;
            /** Grants */
            grants: components["schemas"]["GrantOut"][];
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            /** Last Login */
            last_login: string | null;
            /** Role */
            role: string;
            /** Two Factor Enabled */
            two_factor_enabled: boolean;
            /** Username */
            username: string;
        };
        /** UserPatch */
        UserPatch: {
            /** Is Active */
            is_active?: boolean | null;
            /**
             * Reset 2Fa
             * @default false
             */
            reset_2fa: boolean;
            /** Role */
            role?: string | null;
        };
        /** VenueOut */
        VenueOut: {
            /** Key */
            key: string;
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Long Only */
            long_only: boolean;
            /** Maker Fee */
            maker_fee: number;
            /** Max Leverage */
            max_leverage: number;
            /** Min Qty */
            min_qty: number;
            /** Qty Step */
            qty_step: number;
            /** Quote Asset */
            quote_asset: string;
            /** Supports Live */
            supports_live: boolean;
            /** Taker Fee */
            taker_fee: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    trading_api_list_accounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOut"][];
                };
            };
        };
    };
    trading_api_create_account: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOut"];
                };
            };
        };
    };
    trading_api_get_account: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOut"];
                };
            };
        };
    };
    trading_api_account_equity: {
        parameters: {
            query?: {
                book?: string;
                days?: number;
            };
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquityPoint"][];
                };
            };
        };
    };
    trading_api_move_funds: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FundsIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOut"];
                };
            };
        };
    };
    trading_api_account_ledger: {
        parameters: {
            query?: {
                book?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerOut"][];
                };
            };
        };
    };
    alerts_api_defaults: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleOut"][];
                };
            };
        };
    };
    alerts_api_list_events: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"][];
                };
            };
        };
    };
    alerts_api_list_rules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleOut"][];
                };
            };
        };
    };
    alerts_api_create_rule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleOut"];
                };
            };
        };
    };
    alerts_api_update_rule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleOut"];
                };
            };
        };
    };
    alerts_api_delete_rule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    alerts_api_get_telegram: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramOut"];
                };
            };
        };
    };
    alerts_api_set_telegram: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelegramIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramOut"];
                };
            };
        };
    };
    alerts_api_test_telegram: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    core_api_list_audit: {
        parameters: {
            query?: {
                account_id?: number | null;
                action?: string | null;
                before_id?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditOut"][];
                };
            };
        };
    };
    core_api_two_factor_confirm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    core_api_two_factor_setup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TwoFactorSetupOut"];
                };
            };
        };
    };
    core_api_csrf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    core_api_login_view: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    core_api_logout_view: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    core_api_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    core_api_change_password: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    trading_api_list_bots: {
        parameters: {
            query?: {
                account_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BotOut"][];
                };
            };
        };
    };
    trading_api_new_bot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BotIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BotOut"];
                };
            };
        };
    };
    trading_api_get_bot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bot_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BotOut"];
                };
            };
        };
    };
    trading_api_bot_decisions: {
        parameters: {
            query?: {
                action?: string | null;
                limit?: number;
                before?: string | null;
            };
            header?: never;
            path: {
                bot_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionOut"][];
                };
            };
        };
    };
    trading_api_change_bot_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bot_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BotStatusIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BotOut"];
                };
            };
        };
    };
    trading_api_get_candles: {
        parameters: {
            query?: {
                symbol?: string;
                timeframe?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandleOut"][];
                };
            };
        };
    };
    trading_api_list_fills: {
        parameters: {
            query?: {
                account_id?: number | null;
                bot_id?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeOut"][];
                };
            };
        };
    };
    trading_api_list_orders: {
        parameters: {
            query?: {
                account_id?: number | null;
                status?: string | null;
                bot_id?: number | null;
                book?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOut"][];
                };
            };
        };
    };
    trading_api_place_order: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOut"];
                };
            };
        };
    };
    trading_api_cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOut"];
                };
            };
        };
    };
    trading_api_list_positions: {
        parameters: {
            query?: {
                account_id?: number | null;
                include_flat?: boolean;
                bot_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionOut"][];
                };
            };
        };
    };
    trading_api_close: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOut"];
                };
            };
        };
    };
    trading_api_update_protection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProtectionIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionOut"];
                };
            };
        };
    };
    trading_api_get_quote: {
        parameters: {
            query: {
                venue: string;
                symbol?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteOut"];
                };
            };
        };
    };
    research_api_list_experiments: {
        parameters: {
            query?: {
                strategy?: string | null;
                kind?: string | null;
                decision?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentPage"];
                };
            };
        };
    };
    research_api_decide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentOut"];
                };
            };
        };
    };
    research_api_list_jobs: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"][];
                };
            };
        };
    };
    research_api_create_job: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
        };
    };
    research_api_get_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
        };
    };
    research_api_lifecycle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LifecyclePage"];
                };
            };
        };
    };
    research_api_set_lifecycle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LifecycleIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LifecycleOut"];
                };
            };
        };
    };
    research_api_shadow_history: {
        parameters: {
            query?: {
                strategy_label?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShadowHistory"];
                };
            };
        };
    };
    trading_api_list_strategies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyOut"][];
                };
            };
        };
    };
    trading_api_system_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemOut"];
                };
            };
        };
    };
    core_api_list_users: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
        };
    };
    core_api_create_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    core_api_update_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    core_api_set_grants: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrantIn"][];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    trading_api_list_venues: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VenueOut"][];
                };
            };
        };
    };
}
