# Generated by Django 5.2.17 on 2026-09-30 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('strategy', models.CharField(max_length=40)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('symbol', models.CharField(default='BTC/USDT', max_length=30)),
                ('timeframe', models.CharField(default='1d', max_length=10)),
                ('fee', models.FloatField(default=0.0)),
                ('slippage', models.FloatField(default=0.0003)),
                ('enabled', models.BooleanField(default=True)),
                ('last_bar_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('status_reason', models.CharField(blank=True, max_length=300)),
                ('last_diagnosis', models.JSONField(blank=True, default=dict)),
                ('near_miss_key', models.CharField(blank=True, max_length=80)),
                ('direction', models.CharField(blank=True, max_length=5)),
                ('entry_price', models.FloatField(blank=True, null=True)),
                ('entry_time', models.DateTimeField(blank=True, null=True)),
                ('stop', models.FloatField(blank=True, null=True)),
                ('take_profit', models.FloatField(blank=True, null=True)),
                ('entry_context', models.JSONField(blank=True, default=dict)),
                ('weight', models.FloatField(default=0.0)),
                ('equity', models.FloatField(default=10000.0)),
                ('last_close', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('entry', 'Entry'), ('stop_update', 'Move stop'), ('exit', 'Exit'), ('rebalance', 'Resize'), ('near_miss', 'Near miss')], max_length=12)),
                ('bar_time', models.DateTimeField()),
                ('direction', models.CharField(blank=True, max_length=5)),
                ('price', models.FloatField(blank=True, null=True)),
                ('stop', models.FloatField(blank=True, null=True)),
                ('take_profit', models.FloatField(blank=True, null=True)),
                ('from_weight', models.FloatField(blank=True, null=True)),
                ('to_weight', models.FloatField(blank=True, null=True)),
                ('pnl_pct', models.FloatField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('fear_greed', models.CharField(blank=True, max_length=40)),
                ('imported', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='recommendations.feed')),
            ],
            options={
                'ordering': ['-bar_time', '-id'],
            },
        ),
    ]
