# Generated by Django 5.2.17 on 2026-09-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='repeat_signal_key',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='kind',
            field=models.CharField(choices=[('entry', 'Entry'), ('stop_update', 'Move stop'), ('exit', 'Exit'), ('rebalance', 'Resize'), ('near_miss', 'Near miss'), ('signal_again', 'Signal again')], max_length=12),
        ),
    ]
