# Generated by Django 5.2.17 on 2026-09-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0002_feed_repeat_signal_key_alter_recommendation_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="capital",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feed",
            name="capital_equity_base",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feed",
            name="contract_size",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="feed",
            name="lot_step",
            field=models.FloatField(default=0.01),
        ),
        migrations.AddField(
            model_name="feed",
            name="lots_held",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="feed",
            name="min_lot",
            field=models.FloatField(default=0.01),
        ),
        migrations.AddField(
            model_name="feed",
            name="risk_pct",
            field=models.FloatField(default=0.01),
        ),
    ]
