# Generated by Django 5.2.17 on 2026-10-01 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0003_mt5_lot_sizing"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignalSwitch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("halted", models.BooleanField(default=False)),
                ("reason", models.CharField(blank=True, max_length=300)),
                ("changed_at", models.DateTimeField(blank=True, null=True)),
                ("changed_by", models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name="feed",
            name="halt_reason",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="feed",
            name="halted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="feed",
            name="halted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="kind",
            field=models.CharField(
                choices=[
                    ("entry", "Entry"),
                    ("stop_update", "Move stop"),
                    ("exit", "Exit"),
                    ("rebalance", "Resize"),
                    ("near_miss", "Near miss"),
                    ("signal_again", "Signal again"),
                    ("suppressed", "Signals paused"),
                    ("resumed", "Signals resumed"),
                ],
                max_length=12,
            ),
        ),
    ]
