# Generated by Django 5.2.17 on 2026-10-01 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0004_kill_switch"),
        ("research", "0004_portfolio_job_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feed",
            name="approved_by",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="feed",
            name="approved_config_hash",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="feed",
            name="approved_experiment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="research.experiment",
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="code_version",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="config_hash",
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="data_digest",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="data_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="data_rows",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="data_to",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
