# Generated by Django 5.2.17 on 2026-10-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0005_signal_lineage"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="heads_up_bar",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feed",
            name="heads_up_note",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
