# Generated by Django 5.2.17 on 2026-10-02 08:25

from django.db import migrations, models


def follow_the_ensemble(apps, schema_editor):
    """The owner chose to paper-follow the ensemble on the Exness demo."""
    Feed = apps.get_model("recommendations", "Feed")
    Feed.objects.filter(strategy="donchian_ensemble").update(following=True)


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0006_heads_up"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="following",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(follow_the_ensemble, migrations.RunPython.noop),
    ]
