# Generated by Django 5.2.17 on 2026-09-29 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True)),
                ('kind', models.CharField(max_length=20)),
                ('strategy', models.CharField(db_index=True, max_length=40)),
                ('strategy_label', models.CharField(max_length=80)),
                ('symbol', models.CharField(max_length=30)),
                ('timeframe', models.CharField(max_length=10)),
                ('window_start', models.CharField(blank=True, max_length=40)),
                ('window_end', models.CharField(blank=True, max_length=40)),
                ('touched_holdout', models.BooleanField(default=False)),
                ('config', models.JSONField(default=dict)),
                ('config_hash', models.CharField(max_length=20)),
                ('data_version', models.CharField(blank=True, max_length=120)),
                ('git_commit', models.CharField(blank=True, max_length=40)),
                ('result', models.JSONField(default=dict)),
                ('decision', models.CharField(blank=True, max_length=20)),
                ('decision_reason', models.TextField(blank=True)),
                ('source_id', models.IntegerField(null=True, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShadowRebalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(unique=True)),
                ('strategy_label', models.CharField(db_index=True, max_length=80)),
                ('symbol', models.CharField(max_length=30)),
                ('timeframe', models.CharField(max_length=10)),
                ('bar_time', models.DateTimeField()),
                ('price', models.FloatField()),
                ('from_weight', models.FloatField()),
                ('to_weight', models.FloatField()),
                ('equity', models.FloatField()),
            ],
            options={
                'ordering': ['-bar_time'],
            },
        ),
        migrations.CreateModel(
            name='ShadowTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(unique=True)),
                ('strategy_label', models.CharField(db_index=True, max_length=80)),
                ('symbol', models.CharField(max_length=30)),
                ('timeframe', models.CharField(max_length=10)),
                ('direction', models.CharField(max_length=5)),
                ('entry_time', models.DateTimeField()),
                ('entry_price', models.FloatField()),
                ('exit_time', models.DateTimeField()),
                ('exit_price', models.FloatField()),
                ('pnl_pct', models.FloatField()),
                ('exit_reason', models.CharField(max_length=30)),
                ('context', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-exit_time'],
            },
        ),
        migrations.CreateModel(
            name='ResearchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('backtest', 'Backtest'), ('research_report', 'Research report')], max_length=20)),
                ('params', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='queued', max_length=10)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategyLifecycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80, unique=True)),
                ('stage', models.CharField(choices=[('research', 'research'), ('backtested', 'backtested'), ('holdout_passed', 'holdout passed'), ('shadowing', 'shadowing'), ('shadow_review', 'shadow review'), ('approved', 'approved'), ('automation_ready', 'automation ready'), ('disabled', 'disabled'), ('retired', 'retired')], default='research', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
    ]
