# Generated by Django 5.2.17 on 2026-09-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0003_research_api_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="researchjob",
            name="kind",
            field=models.CharField(
                choices=[
                    ("backtest", "Backtest"),
                    ("research_report", "Research report"),
                    ("portfolio_report", "Portfolio report"),
                ],
                max_length=20,
            ),
        ),
    ]
