# Generated by Django 5.2.17 on 2026-10-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0004_portfolio_job_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="experiment",
            name="returns",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="researchjob",
            name="kind",
            field=models.CharField(
                choices=[
                    ("backtest", "Backtest"),
                    ("research_report", "Research report"),
                    ("portfolio_report", "Portfolio report"),
                    ("walk_forward", "Walk-forward validation"),
                ],
                max_length=20,
            ),
        ),
    ]
