# Generated by Django 5.2.17 on 2026-10-01 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0005_walk_forward"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hypothesis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("statement", models.TextField()),
                ("family", models.CharField(db_index=True, max_length=40)),
                ("pass_criteria", models.JSONField(default=dict)),
                ("trial_budget", models.PositiveIntegerField(default=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("abandoned", "Abandoned"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=10,
                    ),
                ),
                ("conclusion", models.TextField(blank=True)),
                ("created_by", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("concluded_by", models.CharField(blank=True, max_length=150)),
                ("concluded_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="experiment",
            name="hypothesis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="experiments",
                to="research.hypothesis",
            ),
        ),
        migrations.AddField(
            model_name="researchjob",
            name="hypothesis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="research.hypothesis",
            ),
        ),
    ]
