# Generated by Django 5.2.17 on 2026-09-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(max_length=30)),
                ('symbol', models.CharField(max_length=30)),
                ('timeframe', models.CharField(max_length=10)),
                ('open_time', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
            ],
            options={
                'ordering': ['open_time'],
                'indexes': [models.Index(fields=['exchange', 'symbol', 'timeframe', 'open_time'], name='market_cand_exchang_23bf07_idx')],
                'constraints': [models.UniqueConstraint(fields=('exchange', 'symbol', 'timeframe', 'open_time'), name='uniq_candle')],
            },
        ),
        migrations.CreateModel(
            name='FundingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(max_length=30)),
                ('symbol', models.CharField(max_length=30)),
                ('funding_time', models.DateTimeField()),
                ('funding_rate', models.FloatField()),
            ],
            options={
                'ordering': ['funding_time'],
                'constraints': [models.UniqueConstraint(fields=('exchange', 'symbol', 'funding_time'), name='uniq_funding')],
            },
        ),
    ]
