# Generated by Django 5.2.17 on 2026-09-29 19:51

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('mode', models.CharField(choices=[('paper', 'Paper'), ('live', 'Live')], default='paper', max_length=5)),
                ('venue', models.CharField(choices=[('quidax_spot', 'Quidax spot'), ('exness_cfd', 'Exness CFD (paper)')], default='quidax_spot', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('halted', models.BooleanField(default=False)),
                ('halted_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('strategy', models.CharField(max_length=40)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('symbol', models.CharField(default='BTC/USDT', max_length=30)),
                ('timeframe', models.CharField(default='4h', max_length=10)),
                ('allocation', models.DecimalField(decimal_places=10, max_digits=28)),
                ('risk_pct', models.FloatField(default=0.01)),
                ('status', models.CharField(choices=[('running', 'Running'), ('paused', 'Paused'), ('stopped', 'Stopped'), ('error', 'Error')], default='stopped', max_length=10)),
                ('status_reason', models.CharField(blank=True, max_length=300)),
                ('last_bar_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_errors', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bots', to='trading.tradingaccount')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('book', models.CharField(db_index=True, max_length=30)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('bot', 'Bot'), ('stop', 'Stop loss'), ('take_profit', 'Take profit'), ('close', 'Close position'), ('kill_switch', 'Kill switch')], max_length=12)),
                ('symbol', models.CharField(max_length=30)),
                ('side', models.CharField(max_length=4)),
                ('order_type', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=28)),
                ('limit_price', models.DecimalField(blank=True, decimal_places=10, max_digits=28, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('filled', 'Filled'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('filled_quantity', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=28)),
                ('average_price', models.DecimalField(blank=True, decimal_places=10, max_digits=28, null=True)),
                ('fees', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=28)),
                ('venue_order_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('reject_reason', models.CharField(blank=True, max_length=300)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('stop_price', models.DecimalField(blank=True, decimal_places=10, max_digits=28, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=10, max_digits=28, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='trading.bot')),
                ('placed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='trading.tradingaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=10, max_digits=28)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=28)),
                ('fee', models.DecimalField(decimal_places=10, max_digits=28)),
                ('liquidity', models.CharField(max_length=5)),
                ('time', models.DateTimeField(db_index=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fills', to='trading.order')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='PaperVenueOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_order_id', models.CharField(max_length=40, unique=True)),
                ('client_id', models.CharField(max_length=64)),
                ('symbol', models.CharField(max_length=30)),
                ('side', models.CharField(max_length=4)),
                ('order_type', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=28)),
                ('limit_price', models.DecimalField(decimal_places=10, max_digits=28, null=True)),
                ('status', models.CharField(db_index=True, max_length=10)),
                ('fills', models.JSONField(default=list)),
                ('reject_reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_orders', to='trading.tradingaccount')),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(db_index=True, max_length=30)),
                ('kind', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('allocation', 'Allocation'), ('trade', 'Trade'), ('fee', 'Fee'), ('financing', 'Financing')], max_length=12)),
                ('asset', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=28)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='trading.order')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger', to='trading.tradingaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BotDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_time', models.DateTimeField()),
                ('action', models.CharField(choices=[('none', 'No signal'), ('hold', 'Holding'), ('enter', 'Entered'), ('rebalance', 'Rebalanced'), ('skip', 'Skipped'), ('blocked', 'Blocked'), ('error', 'Error')], max_length=10)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('diagnosis', models.JSONField(blank=True, default=dict)),
                ('price', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='trading.bot')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='trading.order')),
            ],
            options={
                'ordering': ['-bar_time'],
                'constraints': [models.UniqueConstraint(fields=('bot', 'bar_time'), name='uniq_bot_decision')],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=30)),
                ('symbol', models.CharField(max_length=30)),
                ('quantity', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=28)),
                ('average_price', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=28)),
                ('stop_price', models.DecimalField(blank=True, decimal_places=10, max_digits=28, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=10, max_digits=28, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('realized_pnl', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=28)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='trading.bot')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='trading.tradingaccount')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account', 'book', 'symbol'), name='uniq_position')],
            },
        ),
        migrations.CreateModel(
            name='PaperBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=28)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_balances', to='trading.tradingaccount')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account', 'asset'), name='uniq_paper_balance')],
            },
        ),
        migrations.CreateModel(
            name='EquitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(blank=True, max_length=30)),
                ('time', models.DateTimeField()),
                ('equity', models.DecimalField(decimal_places=10, max_digits=28)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_snapshots', to='trading.tradingaccount')),
            ],
            options={
                'ordering': ['time'],
                'indexes': [models.Index(fields=['account', 'book', 'time'], name='trading_equ_account_1e918f_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccountGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('trader', 'Trader'), ('viewer', 'Viewer')], default='viewer', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='trading.tradingaccount')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'account'), name='uniq_grant')],
            },
        ),
    ]
