# Generated by Django 5.2.17 on 2026-09-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='near_miss_key',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
