# Generated by Django 5.2.17 on 2026-09-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_bot_near_miss_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='repeat_signal_key',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
