# Generated by Django 5.2.17 on 2026-10-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0003_bot_repeat_signal_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="botdecision",
            name="code_version",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="botdecision",
            name="config_hash",
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
        migrations.AddField(
            model_name="botdecision",
            name="data_digest",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="botdecision",
            name="data_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="botdecision",
            name="data_rows",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="botdecision",
            name="data_to",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
